#!/bin/bash
pids=$(ps -e | grep offlineimap | awk 'BEGIN {ORS=" "} {print $1}')

if [ "$pids" ]; then
  echo "killing offlineimap instances ($pids)" 
  kill $pids
  sleep 10
  kill -9 $pids
  sleep 10
fi

offlineimap -u basic &
